# list_calendar=data.frame()
# 
# for (i in seq(2017,2023,by=1)){
#   
#   list=list_tournament(i)
#   list$Annee=i
#   list_calendar=rbind(list_calendar,list)
#   print(i)
# }
# 
# library(openxlsx)
# 
# wb <- createWorkbook()
# 
# # Ajouter une feuille et écrire les données
# addWorksheet(wb, "List_Tournament")
# writeData(wb, sheet = "List_Tournament", x = list_calendar)
# 
# # Sauvegarder le fichier
# saveWorkbook(wb, file = "list_tournament.xlsx", overwrite = TRUE)
# 
# getwd()


exclusion=c("International Tennis Series",
            "Tennis Point Exhibition Series",
            "Marbello Exhibition Series",
            "Tennis Point Exhibition Series 2",
            "UTR Pro Match Series",
            "Tennis Point Exhibition Series 3",
            "Tennis Point Exhibition Series 4",
            "Tennis Point Series (USA)",
            "Friendship Cup",
            "Tennis Point Exhibition Series 5",
            "Budapest Kupa Exhibition Series",
            "Tennis Point Series 2 (USA)",
            "SK Soccer Cup",
            "CZE TA President's Cup",
            "Grand Slam Tennis Tours MatchPlay",
            "Austrian Pro Series",
            "Tennis Point Exhibition Series 6",
            "UTR Leschly Challenge",
            "East Coast Pro Series",
            "West Coast Pro Series",
            "Baltic Tennis League",
            "New Zealand Premier League",
            "Tennis Point Exhibition Series 7",
            "Valencia challenge",
            "Adriatic Tennis Series",
            "European Pro Tennis Series",
            "TPG Exhibition Series",
            "DTB German Pro Series",
            "UTF Invitational",
            "Tennis Point Exhibition Series 8",
            "Battle of Bradenton",
            "Top League CTS",
            "Adria Tour 2",
            "Ultimate Tennis Showdown",
            "Eastern European Championship",
            "Bratislava Open",
            "Polish National Tour",
            "Swedish Summer Tour",
            "Adria Tour 3",
            "Italian Championship",
            "Campionati Italiani Assoluti",
            "Israel National Tennis Tour",
            "FPT Portugal Series",
            "Macha Lake Open",
            "Tennisportalen Open",
            "Adria Tour 4",
            "Altec Styslinger Tennis Exhibition",
            "Italian National Tour",
            "Austrian Championship",
            "FPT Portugal Series 2",
            "National Tennis Tour Switzerland",
            "Adria Tour",
            "AllAmerican Team Cup",
            "British Tour",
            "Cup of Friendship",
            "ÖTV Challenge Series",
            "Swiss Masters",
            "British Tour 2",
            "Challenge Elite FFT",
            "Polish National Tour 2",
            "Austrian Young Guns",
            "Tennis Point Exhibition Series 9",
            "Thiem's Seven",
            "FPT Portugal Series 3",
            "British Tour 3",
            "Privatbanka Open",
            "Tie-Break Cup Zermatt",
            "Liga MAPFRE de Tenis",
            "World TeamTennis",
            "bett1 Aces",
            "ÖTV Challenge Series 2",
            "Challenge Elite FFT 2",
            "National Championship",
            "Tennis Point Exhibition Series 10",
            "FPT Portugal Series 4",
            "Moravia Open",
            "Liga MAPFRE de Tenis 2",
            "Bett",
            "Liga MAPFRE de Tenis 3",
            "British Tour 4",
            "ÖTV Challenge Series 3",
            "Challenge Elite FFT 3",
            "UK Pro Series 2",
            "GP de la Gruyere",
            "Tennis Point Exhibition Series 11",
            "Liga MAPFRE de Tenis 4",
            "British Tour 5",
            "HSC Cup Piestany",
            "Securitas Pro Cup",
            "Polish National Tour 3",
            "Ultimate Tennis Showdown 2",
            "International Premier League",
            "ÖTV Challenge Series 4",
            "Battle of the Brits 2",
            "UK Pro Series 3",
            "Svijany Open",
            "Liga MAPFRE de Tenis 5",
            "Merko Cup",
            "Polish National Tour 4",
            "Zilina",
            "UK Pro Series 4",
            "Tipsport Elite Trophy",
            "UK Pro Series 5",
            "Polish National Tour 5",
            "Polish National Tour 6",
            "British Tour 6",
            "Copa del Rey",
            "Finnish Tennis Tour",
            "Peugeot Tennis Tour",
            "British Tour 7",
            "British Tour 8",
            "Verbier Open",
            "British Tour 9",
            "British Tour 10",
            "Ultimate Tennis Showdown 3",
            "British Tour 11",
            "Battle of the Brits 3",
            "Delray Beach - seniors",
            "UTR Pro Match Series",
            "UTS Championship",
            "Austrian Bundesliga",
            "Austrian Championship",
            "National Championship",
            "World TeamTennis",
            "UTR Pro Match Series",
            "Melbourne Summer Set 1",
            "Austrian Bundesliga",
            "Liverpool - exhibition",
            "Mediterranean Games",
            "Polish national championship",
            "Villa Maria ITF",
            "Waikiki Cup",
            "Austrian Bundesliga",
            "Netflix Slam",
            "Kooyong - exh.",
            "Abu Dhabi - exh.",
            "Hopman Cup",
            "Adelaide - World Tennis Chall.",
            "Indian Wells - pre-qualifier",
            "Stockholm - seniors",
            "Italian Team Championship",
            "Rome - pre-qualification",
            "Hurlingham - exhibition",
            "Boodles Tennis Challenge",
            "Bundesliga - men",
            "Laver Cup","Mallorca - seniors",
            "Monterrey - seniors",
            "AO WC Playoff - Asia-Pacific",
            "London - seniors",
            "France - Championship",
            "AO Wildcard Playoff - Australia",
            "Czech league",
            "Hong Kong 6 ITF",
            "UK Pro Series",
            "Swiss Nationalliga A",
            "World University Games",
            "Asian Games",
            "Pan American Games",
            "Pacific Games",
            "German Championships",
            "Netherlands - Championship",
            "World Tennis League",
            "Battle of the Brits",
            "Diriyah Tennis Cup",
            "Czech Indoor Championship",
            "Brussels - seniors",
            "Hawaii Open",
            "Basel Open",
            "Atlanta Open",
            "A Day at the Drive (Adelaide)",
            "Int. Premier Tennis League",
            "Czech Championship",
            "Hua Hin - exhibition",
            "US Open pre-qualifier",
            "Antalya-Kaya Belek 10 ITF",
            "Knokke - seniors",	
            "Champions Tennis League",
            "Edinburgh - seniors",
            "AO Wildcard Playoff - USA"
            
)

# list_tournament(2020) %>% filter(Categorie=="ATP")
# 
# start=Sys.time()
# data_rank=rank_scrap(date)
# Sys.time()-start
